image:
  file: .gitpod.dockerfile
ports:
  - port: 8080
    onOpen: open-browser
    visibility: private
    name: App
  - port: 3306
    onOpen: ignore
    visibility: private
    name: MySQL Database
  - port: 6379
    onOpen: ignore
    visibility: private
    name: Redis

tasks:
  - name: App
    command: |
      composer install --no-interaction
      bash scripts/secrets.sh
      set -a
      source scripts/.gitpod.env
      set +a
      gp ports await 3306
      mysql -e "CREATE DATABASE IF NOT EXISTS iclip;"
      mysql -e "CREATE USER IF NOT EXISTS 'interclip'@'localhost' IDENTIFIED BY 'gitpod-local-app-password'; GRANT ALL ON iclip.* TO 'interclip'@'localhost';"
      mysql iclip < scripts/db.sql
      gp ports await 8080
      apachectl restart
      redis-server --requirepass "$REDIS_PASSWORD"
  - name: Apache
    openMode: split-right
    command: >
      sudo cp apache.conf /etc/apache2/apache2.conf &&
      gp ports await 3306 &&
      apachectl start &&
      multitail /var/log/apache2/access.log -I /var/log/apache2/error.log
  - name: Sass compiler
    command: |
      yarn
      yarn compile:styles --watch
  - name: TS Watch
    init: yarn
    command: |
      yarn
      yarn dev

github:
  prebuilds:
    branches: true
    addLabel: gitpod-prebuilt
    addComment: true
    addCheck: true

vscode:
  extensions:
    - bmewburn.vscode-intelephense-client
    - cweijan.vscode-redis-client
