[package]
name = "qr_code_wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
qrcode = "0.12.0"
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen = "0.2.79"

[lib]
crate-type = ["cdylib"]
