name: File format
on:
  push:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  format:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22.x
      - run: yarn install --frozen-lockfile
      - run: >-
          yarn prettier --check
          .devcontainer/devcontainer.json
          .devcontainer/compose.yaml
          .github/workflows/*.yml
          api/facts.js
          api/worker.js
          docker-compose.yaml
          js/admin.ts
          js/file.ts
          js/get.ts
          js/index.ts
          js/menu.ts
          js/new.ts
          package.json
          scripts/cachePurge.ts
